// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvUyT-khN3x7YB9_4dQx0SDW8ZxoRT0VA',
    appId: '1:484615395564:web:4f88c6bf3419d10c93edc9',
    messagingSenderId: '484615395564',
    projectId: 'rawan-dv',
    authDomain: 'rawan-dv.firebaseapp.com',
    storageBucket: 'rawan-dv.appspot.com',
    measurementId: 'G-401Q3JEQ5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsCj49o22IZBkUsPK0n0B7EKltIKtZjf0',
    appId: '1:484615395564:android:31be8988b4c99d8793edc9',
    messagingSenderId: '484615395564',
    projectId: 'rawan-dv',
    storageBucket: 'rawan-dv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYFEwjq2W6-DQ98J5cb27fxZSFWkYw6xg',
    appId: '1:484615395564:ios:3c6bd950391976a693edc9',
    messagingSenderId: '484615395564',
    projectId: 'rawan-dv',
    storageBucket: 'rawan-dv.appspot.com',
    iosBundleId: 'com.example.firebseConnection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYFEwjq2W6-DQ98J5cb27fxZSFWkYw6xg',
    appId: '1:484615395564:ios:3c6bd950391976a693edc9',
    messagingSenderId: '484615395564',
    projectId: 'rawan-dv',
    storageBucket: 'rawan-dv.appspot.com',
    iosBundleId: 'com.example.firebseConnection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvUyT-khN3x7YB9_4dQx0SDW8ZxoRT0VA',
    appId: '1:484615395564:web:04e75b522d21b90e93edc9',
    messagingSenderId: '484615395564',
    projectId: 'rawan-dv',
    authDomain: 'rawan-dv.firebaseapp.com',
    storageBucket: 'rawan-dv.appspot.com',
    measurementId: 'G-EHEGTPM4TJ',
  );
}
